### ISSUE TITLE
An error has occurred.

### ISSUE THREAD

**Issue by negan7879** [skgyu/SpaceshipNet#3]
out = torch.linalg.solve(A.to(dtype), B.to(dtype))
RuntimeError: CUDA error: misaligned address
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

It seems to be a kornia issue, what version are you on?

**Comment by skgyu** [comment]
We use kornia version 0.5.11 on RTX 3090 (python3.7) and kornia version 0.6.12 on A100 (python 3.8).
